import type { Suggestion } from '../../types';
import Card from '../../components/Card';
import Button from '../../components/Button';
import SuggestionCard from './SuggestionCard';

interface SuggestionsPanelProps {
  suggestions: Suggestion[];
  loading: boolean;
  error: string | null;
  busySuggestionId?: string | null;
  busyAction?: 'apply' | 'reject' | null;
  onRefresh: () => void;
  onApply: (suggestionId: string) => void;
  onReject: (suggestionId: string) => void;
}

export default function SuggestionsPanel({
  suggestions,
  loading,
  error,
  busySuggestionId = null,
  busyAction = null,
  onRefresh,
  onApply,
  onReject,
}: SuggestionsPanelProps) {
  return (
    <Card
      title="AI Suggestions"
      subtitle="Allow, deny, and rule-edit recommendations generated by the AI policy engine"
      actions={
        <Button size="sm" variant="secondary" onClick={onRefresh}>
          Refresh
        </Button>
      }
    >
      {loading ? (
        <p className="text-sm text-gray-500">Loading suggestions...</p>
      ) : error ? (
        <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>
      ) : suggestions.length === 0 ? (
        <div className="rounded-md border border-dashed border-gray-300 bg-gray-50 px-4 py-6 text-center text-sm text-gray-500">
          No pending AI suggestions right now.
        </div>
      ) : (
        <div className="space-y-3">
          {suggestions.map((suggestion) => (
            <SuggestionCard
              key={suggestion.id}
              suggestion={suggestion}
              busyAction={busySuggestionId === suggestion.id ? busyAction : null}
              onApply={onApply}
              onReject={onReject}
            />
          ))}
        </div>
      )}
    </Card>
  );
}
